volumes:
  tg_pg_data:

services:
  db:
    image: postgres:16.4
    container_name: DataBase
    env_file:
      - .env
    volumes:
      - tg_pg_data:/var/lib/postgresql/pg_data
  
  migrations:
    build: ./src/
    container_name: Migrations
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "alembic upgrade head"

  local_service:
    build: ./src/
    container_name: LocalService
    env_file:
      - .env
    depends_on:
      - migrations
  
  remote_service:
    container_name: RemoteService
    build: ./remote_service/
    ports:
      - '9000:9000'
    depends_on:
      - local_service
  
  gateway:
    image: nginx
    container_name: gateway
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - '8000:80'
    depends_on:
      - remote_service
