"""Add user relationship to Query

Revision ID: 476a28c0b5c1
Revises: 06954682c8c1
Create Date: 2024-10-30 21:45:33.891817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476a28c0b5c1'
down_revision: Union[str, None] = '06954682c8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'query', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.drop_column('query', 'user_id')
    # ### end Alembic commands ###
